apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: appinfo-canary-broken
  labels:
    releaes: canary
    app:  appinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appinfo
  template:
    metadata:
      labels:
        app: appinfo
        release: canary
    spec:
      containers:
      - name: appinfo-containers
        image: runyonsolutions/appinfo:2
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: podinfo
            mountPath: /etc
            readOnly: false
      volumes:
          - name: podinfo
            downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels